### PR TITLE
Quote paths in post-link scripts to fix errors when space is in path.

### LINKED ISSUE #8: Errors with post-link script if a space is in the conda path
Issue:
If a user has a space in their conda path, the post-link script will fail with ".... is not recognized as an internal or external command" because it tries to run the partial path before the space as a program.

The fix should be to quote the command path in the post-link script.
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #8

### CODE REVIEW

**Comment by tschoonj** [comment]
Looks like something went wrong in https://github.com/conda-forge/gobject-introspection-feedstock/pull/21. Investigating...

**Comment by ryanvolz** [comment]
Seeing this error on Windows in a couple places now. It is almost certainly related to the new `gobject-introspection` `1.64.1`.

**Comment by tschoonj** [comment]
There is something strange going on: when installing the latest gobject-introspection not all occurrences of the gobject-introspection build path are replaced with the new environment.

**Comment by tschoonj** [comment]
For example the build fails at:

```

FAILED: gdk/Gdk-3.0.gir 
"D:/bld/gobject-introspection_1590945570124/_h_env/python.exe" "D:/bld/gtk3_1591039266330/_h_env/Library/bin/g-ir-scanner" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/gobject-introspection-1.0" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/glib-2.0" "-ID:/bld/gtk3_1591039266330/_h_env/Library/lib/glib-2.0/include" "--no-libtool" "--namespace=Gdk" "--nsversion=3.0" "--warn-all" "--output" "gdk/Gdk-3.0.gir" "--c-include=gdk/gdk.h" "--quiet" "-DGDK_COMPILATION" "-ID:/bld/gtk3_1591039266330/work/gdk" "-ID:/bld/gtk3_1591039266330/work/builddir/gdk" "-I./." "-I../." "-I./gdk/x11" "-I../gdk/x11" "-I./gdk/." "-I../gdk/." "--filelist=D:/bld/gtk3_1591039266330/work/builddir/gdk/ffe01f7@@gdk-3@sha/Gdk_3.0_gir_filelist" "--include=cairo-1.0" "--include=Gio-2.0" "--include=GdkPixbuf-2.0" "--include=Pango-1.0" "--symbol-prefix=gdk" "--identifier-prefix=Gdk" "--pkg-export=gdk-3.0" "--cflags-begin" "-DG_LOG_USE_STRUCTURED=1" "-DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_56" "-DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_58" "-DGTK_VERSION=\"3.24.17\"" "-D_GNU_SOURCE" "-DG_DISABLE_CAST_CHECKS" "-FImsvc_recommended_pragmas.h" "-D_USE_MATH_DEFINES" "-I./." "-I../." "-I./gdk/x11" "-I../gdk/x11" "-I./gdk/." "-I../gdk/." "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/gdk-pixbuf-2.0" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/glib-2.0" "-ID:/bld/gtk3_1591039266330/_h_env/Library/lib/glib-2.0/include" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/cairo" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/pango-1.0" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/fribidi" "-ID:/bld/gtk3_1591039266330/_h_env/Library/include/gio-win32-2.0" "--cflags-end" "--library" "gdk-3" "-LD:/bld/gtk3_1591039266330/work/builddir/gdk" "-LD:/bld/gtk3_1591039266330/_h_env/Library/lib" "-LD:/bld/gtk3_1591039266330/_h_env/Library/lib" "-lgdk_pixbuf-2.0" "-lgio-2.0" "-lintl" "-liconv" "-lshlwapi" "-ldnsapi" "-liphlpapi" "-lws2_32" "-lgmodule-2.0" "-lz" "-lgobject-2.0" "-llibffi" "-lglib-2.0" "-lpcre" "-lwinmm" "-lcairo" "-lpango-1.0" "-lfribidi" "-lcairo-gobject" "-lepoxy" "-lopengl32" "-lgdi32" "-lpangocairo-1.0" "-lpangowin32-1.0" "-lusp10" "-ladvapi32" "-lcomctl32" "-ldwmapi" "-limm32" "-lsetupapi"
CreateProcess failed: The system cannot find the file specified.
```

Here `D:/bld/gobject-introspection_1590945570124` should have been replaced with `D:/bld/gtk3_1591039266330`

**Comment by ryanvolz** [comment]
Aha! There have been issues with conda-build on Windows and build prefix replacement for a few releases. We probably avoided it with the earlier `gobject-introspection` build because it used an earlier conda-build. See https://github.com/conda/conda-build/issues/3909.

**Comment by ryanvolz** [comment]
I suspect that the latest meson is still broken as well, for another reason that's reported in an open bug in the meson feedstock.

**Comment by tschoonj** [comment]
> I suspect that the latest meson is still broken as well, for another reason that's reported in an open bug in the meson feedstock.

This was a desperate attempt from me 😄

**Comment by tschoonj** [comment]
> Aha! There have been issues with conda-build on Windows and build prefix replacement for a few releases. We probably avoided it with the earlier `gobject-introspection` build because it used an earlier conda-build. See [conda/conda-build#3909](https://github.com/conda/conda-build/issues/3909).

I wasn't aware of this. Looks like a rather serious bug. Hope this gets fixed soon.

**Comment by tschoonj** [comment]
I think this is somehow causing it:

```
% head -1 gobject-introspection-1.*/Library/bin/g-ir-scanner
==> gobject-introspection-1.58.2/Library/bin/g-ir-scanner <==
#!/usr/bin/env D:/bld/gobject-introspection_1584985264472/_h_env/python.exe

==> gobject-introspection-1.64.1/Library/bin/g-ir-scanner <==
#!/usr/bin/env D:\bld\gobject-introspection_1590945570124\_h_env\python.exe
```

In the second case, the path does not get updated upon installation, even though it is mentioned in `info/has_prefix`

```
"D:/bld/gobject-introspection_1590945570124/_h_env" text "Library/bin/g-ir-annotation-tool"
"D:/bld/gobject-introspection_1590945570124/_h_env" text "Library/bin/g-ir-scanner"
"D:/bld/gobject-introspection_1590945570124/_h_env" text "Library/lib/pkgconfig/gobject-introspection-1.0.pc"
"D:/bld/gobject-introspection_1590945570124/_h_env" text "Library/lib/pkgconfig/gobject-introspection-no-export-1.0.pc"
"D:\bld\gobject-introspection_1590945570124\_h_env" text "Library/bin/g-ir-annotation-tool"
"D:\bld\gobject-introspection_1590945570124\_h_env" text "Library/bin/g-ir-scanner"
```

I'm tempted to fix this with a bit of `sed` magic in the `gobject-introspection` recipe... What do you think?

**Comment by ryanvolz** [comment]
I've seen something like that before, and it may actually be unrelated to the recent problems with conda-build and prefix replacement. I think this is older. You'll note that in the has_prefix list, both `g-ir-scanner` and `g-ir-annotation-tool` appear twice, with forward slashes in the prefix in one and backward slashes in the other. Having both forward and backward slashes in the file is what breaks the replacement. If we can fix the recipe so that only one direction of slash ends up in those files, I think the prefix replacement will work.

**Comment by ryanvolz** [comment]
I have managed a fix for `gobject-introspection` that is now in a pull request: https://github.com/conda-forge/gobject-introspection-feedstock/pull/22

**Comment by tschoonj** [comment]
Many thanks @ryanvolz for the fix!

**Comment by tschoonj** [comment]
By the way, the g-ir-scanner meson problems might be solved in the next release: https://github.com/mesonbuild/meson/issues/7051

**Pull request merged**
