### PR TITLE
Rely on run_exports, esp. only depend on libglib in run

### PR DESCRIPTION
**Pull request by xhochy**
This removes the implicit python dependency in `run`.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Didn't see the post-link scripts :( . We need to get rid of them to get rid of python at runtime.

**Comment by tschoonj** [comment]
The three commands that are invoked in the post-install scripts are all compiled executables so it should be possible to drop the python dependency entirely. Perhaps moving `glib-compile-schemas` to `libglib` would fix things?

**Comment by ryanvolz** [comment]
> The three commands that are invoked in the post-install scripts are all compiled executables so it should be possible to drop the python dependency entirely. Perhaps moving `glib-compile-schemas` to `libglib` would fix things?

This looks like it should be the fix to me. For instance, Debian includes `glib-compile-schemas` in its base-level libglib package: https://salsa.debian.org/gnome-team/glib/-/blob/debian/master/debian/libglib2.0-0.install.

Otherwise, I'm very happy to see this cleanup!

**Comment by xhochy** [comment]
PR over at glib: https://github.com/conda-forge/glib-feedstock/pull/82

**Pull request merged**
