### PR TITLE
Fix circular dependency with pygobject with testing

### PR DESCRIPTION
**Pull request by ryanvolz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tschoonj** [comment]
Not a fan of this. We should really test if the gobject-intropection typelib works properly by importing them in python.

Where is this causing problems at the moment?

**Comment by ryanvolz** [comment]
> Not a fan of this. We should really test if the gobject-intropection typelib works properly by importing them in python.

It should do this still, just by another mechanism. These imports are tested in the `pygobject` tests, and the `downstreams` mechanism should install `pygobject`, run its tests, and fail if the tests fail. The only case it doesn't fail is if it can't install a compatible `pygobject`, which should only happen when we are expanding to a new platform.

Admittedly, I've never used the `downstreams` feature before, so we should see how these builds go and if it works as expected.

> Where is this causing problems at the moment?

No actual problem with the circular dependency yet, but only because the tests aren't actually run for the `osx_arm64` build. If they were, it would fail because `pygobject` is not available (yet).

It's also gumming up the `pango 1.48` migration, where the bot is erroring out because of the above and failing to issue the migration PR for `gtk3`. I only noticed this because I'm trying to install some new packages and the solver is failing because some things (in this instance `wxwidgets`) haven't been migrated to the new pango yet.

**Comment by tschoonj** [comment]
Do you have any plans to make similar changes to other GNOME recipes as well? I have introduced this kind of test in a couple of feedstocks already...

**Comment by ryanvolz** [comment]
I like those sort of changes; anything with more tests is good! I don't know if any of them would also result in circular dependencies like this, but I think we'd be OK to just handle those situations if/when they come up (like this with the `pango` migration). At least a fix shouldn't be too hard if there are problems. So I say keep on putting in those changes!

It looks like this `downstreams` feature is working as described: the `gtk3` tests are run, and then a separate test sequence happens where `pygobject` is installed and its tests are run. The only thing I'm not sure of is what happens when those `pygobject` tests fail, as I hope they would fail the build just as if the tests were included in `gtk3`. I think I will have to go look in the `conda-build` code to figure that out, and I'll go do that now. If it were to fail when those tests fail as we hope, are you OK with me merging this?

**Comment by tschoonj** [comment]
I wonder if it would perhaps make more sense to get rid of the use of gtk3 in the pygobject test itself. That should also fix the circular dependency right?

**Comment by ryanvolz** [comment]
Yeah, so remove `gtk3` and the stuff in the `pygobject` test that references `gtk3` and have it here instead much like it is currently? I think that would fix the circular dependency, but in the other way where we'd have to build `pygobject` before `gtk3` instead of the other way around for a new platform. I don't know if that ordering is good or bad, but it would work.

It *doesn't* fix my immediate problem with the `pango` migration, but I'm also trying to fix that by getting `pygobject` building for `osx_arm64`.

Is it best to say that your concern with the way this PR changes things is that it makes it non-obvious and dependent on the `pygobject` recipe that the `gobject-introspection` typlib stuff for `gtk3` is getting tested? Is there another way to test that with just `gobject-introspection` and not pulling in `pygobject`? I think in an ideal world we would remove both the `pygobject` and `gtk3` test dependencies from each other as otherwise they are independent.

By the way, I can confirm that `conda-build` does what we expect and fails the build if the `downstreams` tests fail.

**Comment by tschoonj** [comment]
> Yeah, so remove `gtk3` and the stuff in the `pygobject` test that references `gtk3` and have it here instead much like it is currently? I think that would fix the circular dependency, but in the other way where we'd have to build `pygobject` before `gtk3` instead of the other way around for a new platform. I don't know if that ordering is good or bad, but it would work.
> 

I think it makes sense to have a working build of `pygobject` on a new platform before having one of `gtk3`. I would argue that ensuring usage of these GNOME libraries from Python is essential. So IMHO best to modify the `pygobject` tests instead of this PR.

> It _doesn't_ fix my immediate problem with the `pango` migration, but I'm also trying to fix that by getting `pygobject` building for `osx_arm64`.
> 
> Is it best to say that your concern with the way this PR changes things is that it makes it non-obvious and dependent on the `pygobject` recipe that the `gobject-introspection` typlib stuff for `gtk3` is getting tested? Is there another way to test that with just `gobject-introspection` and not pulling in `pygobject`? I think in an ideal world we would remove both the `pygobject` and `gtk3` test dependencies from each other as otherwise they are independent.
> 

Feel free to remove the `pygobject` downstreams test in `gobject-introspection`. This would indeed be a chicken-and-egg problem for new platforms.

In my experience, you really need to run the imports with pygobject and try a couple of classes to ensure that they actually work. On Windows, I had a lot of trouble with `libgraphene` and `harfbuzz`, as the typelibs were produced without errors but didn't contain all symbols, unless built with VS2019....

> By the way, I can confirm that `conda-build` does what we expect and fails the build if the `downstreams` tests fail.

**Comment by ryanvolz** [comment]
> Feel free to remove the `pygobject` downstreams test in `gobject-introspection`. This would indeed be a chicken-and-egg problem for new platforms.

Oh, that wasn't what I meant and I didn't even know that was one of the changes you had done. I think that makes sense to stay.

What I was driving at was if there was a way to test the GI typelibs produced by the `gtk3` package without getting `pygobject` involved. So that we wouldn't have to have a (testing) `pygobject` dependency that is otherwise not required, which would allow migrations and whatnot to work in parallel.

But from your last reply, I read that you think the Python bit is still important to test or that there is no test without `pygobject` that does the job. Is that right? Something like running `g-ir-inspect` doesn't do enough actual testing to catch the situations you're talking about on Windows?

**Comment by tschoonj** [comment]
`g-ir-inspect` is next to useless as it can only tell you which shared libraries or other typelibs it depends on.

AFAIK the only way to make sure that the typelib works is by importing it with pygobject and do a couple of calls on its contents.

To be honest, I use the gtk stack in conda-forge exclusively through pygobject, so it is essential for me that that part works flawlessly.

**Comment by ryanvolz** [comment]
Thanks for the discussion @tschoonj! I'm going to close this now in favor of removing `gtk3` as a test dependency from `pygobject`, which is in progress over at https://github.com/conda-forge/pygobject-feedstock/pull/35 as part of the OSX ARM migrator for fixing the issue of the `pango` migration being held up. I do want to make sure that we test that the GI typelibs work, and keeping `gtk3` as-is will do that just fine with the `pygobject` change.

**Pull request closed without merging**
